// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rueazmqvrqtpwjhhnshk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ1ZWF6bXF2cnF0cHdqaGhuc2hrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0NjIzOTQsImV4cCI6MjA2NDAzODM5NH0.fv4cOnKPSXeTZahKULjCGr6O8Vj_VyIV12WDBlMTJXg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);